version: '3.4'
services:
  homespeaker.server2:
    container_name: homespeaker
    image: homespeakerserver2
    build:
      context: .
      dockerfile: HomeSpeaker.Server2/Dockerfile
    restart: unless-stopped
    devices:
    - /dev/snd:/dev/snd
    ports:
    - 80:80
    - 443:443
    volumes:
    - "/home/piuser/music:/music"
    - "/home/piuser/cert:/certs"
    - "/sys/class/backlight/10-0045:/sys/class/backlight/10-0045"
    - airplay-shared:/tmp/airplay-shared  # Shared volume for AirPlay state
    - /run/user/1000/pulse:/run/user/1000/pulse:rw
    depends_on:
    - aspire    
    environment:
    - MediaFolder=/music
    - ALSA_CARD=Headphones
    - SqliteConnectionString=Data Source=/music/HomeSpeaker.db
    - ASPNETCORE_URLS=https://+443;http://+:80
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/certificate.pfx
    - FFMpegLocation=/usr/bin/ffmpeg
    - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire:18889
    - OTEL_SERVICE_NAME=HomeSpeaker
    - NIGHTSCOUT_URL=https://janedoe.azurewebsites.net
    - Temperature__ApiKey=${GOVEE_API_KEY}
    - PULSE_SERVER=unix:/run/user/1000/pulse/native
    networks:
      speakernet:

  aspire:
    container_name: aspire
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
    - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
    - 18888:18888 # web
    - 4317:18889  # OTLP
    networks:
      speakernet:

  airplay-receiver:
    image: mikebrady/shairport-sync:latest
    container_name: homespeaker-airplay
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./shairport-sync.conf:/etc/shairport-sync.conf:ro
      - airplay-shared:/tmp/airplay-shared  # Shared volume for state files
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - AIRPLAY_NAME=${AIRPLAY_NAME:-HomeSpeaker}
    command: |
      sh -c "
        # Set AirPlay name from environment variable
        AIRPLAY_NAME=\"$${AIRPLAY_NAME:-HomeSpeaker}\"
        
        # Create state management scripts inside container
        cat > /usr/local/bin/airplay-start.sh << 'EOF'
        #!/bin/sh
        echo 'ACTIVE' > /tmp/airplay-shared/state
        echo 'AirPlay session started' > /tmp/airplay-shared/log
        EOF
        
        cat > /usr/local/bin/airplay-stop.sh << 'EOF'
        #!/bin/sh
        echo 'INACTIVE' > /tmp/airplay-shared/state
        echo 'AirPlay session ended' > /tmp/airplay-shared/log
        EOF
        
        chmod +x /usr/local/bin/airplay-start.sh
        chmod +x /usr/local/bin/airplay-stop.sh
        
        # Update the config file with the correct name
        sed -i \"s/name = \\\"HomeSpeaker\\\"/name = \\\"$$AIRPLAY_NAME\\\"/g\" /etc/shairport-sync.conf
        
        # Start shairport-sync
        exec shairport-sync -c /etc/shairport-sync.conf
      "
    depends_on:
      - homespeaker.server2

networks:
 speakernet:

volumes:
  airplay-shared:
