version: '3.4'
services:
  homespeaker.server2:
    container_name: homespeaker
    image: homespeakerserver2
    build:
      context: .
      dockerfile: HomeSpeaker.Server2/Dockerfile
    restart: unless-stopped
    volumes:
      - "/home/piuser/music:/music"
      - "/home/piuser/cert:/certs"
      - "/sys/class/backlight/10-0045:/sys/class/backlight/10-0045"
      - /tmp/airplay-state:/tmp/airplay-state:rw
      - /tmp/airplay-status:/tmp/airplay-status:rw
      - /tmp/shairport-sync-metadata:/tmp/shairport-sync-metadata:rw
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
    ports:
      - 80:80
      - 443:443
    depends_on:
      - aspire    
    environment:
      - MediaFolder=/music
      - ALSA_CARD=Headphones
      - SqliteConnectionString=Data Source=/music/HomeSpeaker.db
      - ASPNETCORE_URLS=https://+443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/certificate.pfx
      - FFMpegLocation=/usr/bin/ffmpeg
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire:18889
      - OTEL_SERVICE_NAME=HomeSpeaker
      - NIGHTSCOUT_URL=https://janedoe.azurewebsites.net
      - Temperature__ApiKey=${GOVEE_API_KEY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    networks:
      - speakernet

  aspire:
    container_name: aspire
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - 18888:18888 # web
      - 4317:18889  # OTLP
    networks:
      - speakernet

  airplay-receiver:
    image: mikebrady/shairport-sync:latest
    container_name: homespeaker-airplay
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./shairport-sync.conf:/etc/shairport-sync.conf:ro
      - ./scripts:/usr/local/bin:ro
      - /tmp/airplay-state:/tmp/airplay-state:rw
      - /tmp/airplay-status:/tmp/airplay-status:rw
      - /tmp/shairport-sync-metadata:/tmp/shairport-sync-metadata:rw
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    depends_on:
      - homespeaker.server2

networks:
  speakernet:
