// <auto-generated />
using System;
using HomeSpeaker.Server2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeSpeaker.Server2.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20260514202804_AddOfflineDownloadTargets")]
    partial class AddOfflineDownloadTargets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiGenreDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("SortOrder");

                    b.ToTable("AiGenreDefinitions");

                    b.HasData(
                        new
                        {
                            Key = "peaceful-instrumental",
                            Description = "Calm instrumental tracks for quiet moments.",
                            DisplayName = "Peaceful Instrumental",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Key = "quiet-sunday",
                            Description = "Gentle vocals and soft arrangements for restful days.",
                            DisplayName = "Quiet Sunday",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Key = "driving-tunes",
                            Description = "Steady rhythm and forward momentum for the road.",
                            DisplayName = "Driving Tunes",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Key = "choral",
                            Description = "Choral harmonies and choir-led arrangements.",
                            DisplayName = "Choral",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Key = "upbeat-a-cappella",
                            Description = "Vocal-driven, energetic a cappella performances.",
                            DisplayName = "Upbeat A Cappella",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Key = "country",
                            Description = "Country storytelling with warm acoustic textures.",
                            DisplayName = "Country",
                            IsActive = true,
                            SortOrder = 6
                        },
                        new
                        {
                            Key = "quiet-classical",
                            Description = "Soft classical pieces and reflective orchestral work.",
                            DisplayName = "Quiet Classical",
                            IsActive = true,
                            SortOrder = 7
                        },
                        new
                        {
                            Key = "church-christmas",
                            Description = "Traditional church Christmas recordings and arrangements.",
                            DisplayName = "Church Christmas",
                            IsActive = true,
                            SortOrder = 8
                        },
                        new
                        {
                            Key = "hymns",
                            Description = "Classic hymns and worship standards.",
                            DisplayName = "Hymns",
                            IsActive = true,
                            SortOrder = 9
                        },
                        new
                        {
                            Key = "classical-christmas",
                            Description = "Classical takes on holiday repertoire.",
                            DisplayName = "Classical Christmas",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            Key = "vocal-christmas",
                            Description = "Vocal-forward holiday performances.",
                            DisplayName = "Vocal Christmas",
                            IsActive = true,
                            SortOrder = 11
                        },
                        new
                        {
                            Key = "worship-ensemble",
                            Description = "Full-band worship and ensemble recordings.",
                            DisplayName = "Worship Ensemble",
                            IsActive = true,
                            SortOrder = 12
                        },
                        new
                        {
                            Key = "reflective-piano",
                            Description = "Solo piano and reflective keys-driven pieces.",
                            DisplayName = "Reflective Piano",
                            IsActive = true,
                            SortOrder = 13
                        },
                        new
                        {
                            Key = "family-singalong",
                            Description = "Upbeat, communal songs for family listening.",
                            DisplayName = "Family Singalong",
                            IsActive = true,
                            SortOrder = 14
                        },
                        new
                        {
                            Key = "warm-folk-acoustic",
                            Description = "Warm acoustic folk with organic instrumentation.",
                            DisplayName = "Warm Folk Acoustic",
                            IsActive = true,
                            SortOrder = 15
                        });
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiPlaybackFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSongPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SongPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SongPath");

                    b.ToTable("AiPlaybackFeedbacks");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiPlaybackSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAdvancedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedSongPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("IsActive", "StartedUtc");

                    b.ToTable("AiPlaybackSessions");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiProcessingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedTracks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentBatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedTracks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScanUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingTracks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueuedTracks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("AiProcessingRuns");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiProcessingWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SongPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SongPath")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresUtc");

                    b.ToTable("AiProcessingWorkItems");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiTrackGenreScore", b =>
                {
                    b.Property<string>("SongPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Why")
                        .HasColumnType("TEXT");

                    b.HasKey("SongPath", "GenreKey");

                    b.HasIndex("GenreKey");

                    b.ToTable("AiTrackGenreScores");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiTrackMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("MarkerKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MarkerValue")
                        .HasColumnType("REAL");

                    b.Property<string>("SongPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SongPath", "MarkerKey");

                    b.ToTable("AiTrackMarkers");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiTrackProfile", b =>
                {
                    b.Property<string>("SongPath")
                        .HasColumnType("TEXT");

                    b.Property<double>("Acousticness")
                        .HasColumnType("REAL");

                    b.Property<string>("AnalysisVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<double>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<double>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Instrumentalness")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastAnalyzedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryMood")
                        .HasColumnType("TEXT");

                    b.Property<double>("Sacredness")
                        .HasColumnType("REAL");

                    b.Property<double>("SeasonalityChristmas")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoLabel")
                        .HasColumnType("TEXT");

                    b.Property<double>("VocalPresence")
                        .HasColumnType("REAL");

                    b.Property<double>("Warmth")
                        .HasColumnType("REAL");

                    b.HasKey("SongPath");

                    b.HasIndex("Status", "LastAnalyzedUtc");

                    b.ToTable("AiTrackProfiles");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AiTrackSimilarity", b =>
                {
                    b.Property<string>("SongPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimilarSongPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonsJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SongPath", "SimilarSongPath");

                    b.HasIndex("SongPath", "Score");

                    b.ToTable("AiTrackSimilarities");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.AnchorDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("AnchorDefinitions");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.DailyAnchorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnchorDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnchorDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnchorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date", "IsCompleted");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("DailyAnchors");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.Impression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SongPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayedBy");

                    b.HasIndex("SongPath");

                    b.HasIndex("Timestamp");

                    b.ToTable("Impressions");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.OfflineDownloadTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SongPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "ArtistName", "AlbumName", "SongPath")
                        .IsUnique();

                    b.ToTable("OfflineDownloadTargets");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysShuffle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.PlaylistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SongPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("PlaylistId", "SongPath");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.RadioStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FaviconFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name");

                    b.HasIndex("PlayCount")
                        .IsDescending();

                    b.ToTable("RadioStreams");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.Thumbnail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artist", "Album");

                    b.ToTable("Thumbnails");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.UserAnchorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnchorDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnchorDefinitionId");

                    b.HasIndex("UserId", "AnchorDefinitionId")
                        .IsUnique();

                    b.ToTable("UserAnchors");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.PlaylistItem", b =>
                {
                    b.HasOne("HomeSpeaker.Server2.Data.Playlist", null)
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.UserAnchorEntity", b =>
                {
                    b.HasOne("HomeSpeaker.Server2.Data.AnchorDefinitionEntity", "AnchorDefinition")
                        .WithMany()
                        .HasForeignKey("AnchorDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnchorDefinition");
                });

            modelBuilder.Entity("HomeSpeaker.Server2.Data.Playlist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
